- fix --enable-small-net bustage - stop defining HAVE_* that we don't use - condense a set of two similar conditionals into one - remove double sets of braces around IPv6 test program - remove question marks on the summary output and remove the old "Server is configured with" line and put it in the same format as the rest of the summary
Reviewed by: stu

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2075,12 +2075,12 @@ if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (exit $ac_status); }; }; then
   for ac_declaration in \
    ''\
-   '#include <stdlib.h>' \
    'extern "C" void std::exit (int) throw (); using std::exit;' \
    'extern "C" void std::exit (int); using std::exit;' \
    'extern "C" void exit (int) throw ();' \
    'extern "C" void exit (int);' \
-   'void exit (int);'
+   'void exit (int);' \
+   '#include <stdlib.h>'
 do
   cat >conftest.$ac_ext <<_ACEOF
 #line $LINENO "configure"
@@ -4501,17 +4501,13 @@ fi
 echo "$as_me:$LINENO: result: $ac_cv_type_u_int32_t" >&5
 echo "${ECHO_T}$ac_cv_type_u_int32_t" >&6
 if test $ac_cv_type_u_int32_t = yes; then
-
-cat >>confdefs.h <<_ACEOF
-#define HAVE_U_INT32_T 1
-_ACEOF
-
-
+  :
 else
-  { { echo "$as_me:$LINENO: error: u_int32_t is not defined, aborting" >&5
-echo "$as_me: error: u_int32_t is not defined, aborting" >&2;}
+  { { echo "$as_me:$LINENO: error: u_int32_t is not defined; aborting" >&5
+echo "$as_me: error: u_int32_t is not defined; aborting" >&2;}
    { (exit 1); exit 1; }; }
 fi
+
 echo "$as_me:$LINENO: checking for unsigned int" >&5
 echo $ECHO_N "checking for unsigned int... $ECHO_C" >&6
 if test "${ac_cv_type_unsigned_int+set}" = set; then
@@ -4560,15 +4556,10 @@ fi
 echo "$as_me:$LINENO: result: $ac_cv_type_unsigned_int" >&5
 echo "${ECHO_T}$ac_cv_type_unsigned_int" >&6
 if test $ac_cv_type_unsigned_int = yes; then
-
-cat >>confdefs.h <<_ACEOF
-#define HAVE_UNSIGNED_INT 1
-_ACEOF
-
-
+  :
 else
-  { { echo "$as_me:$LINENO: error: u_int32_t is not defined, aborting" >&5
-echo "$as_me: error: u_int32_t is not defined, aborting" >&2;}
+  { { echo "$as_me:$LINENO: error: unsigned int is not defined; aborting" >&5
+echo "$as_me: error: unsigned int is not defined; aborting" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
@@ -4621,9 +4612,10 @@ echo "$as_me:$LINENO: result: $ac_cv_type_uintptr_t" >&5
 echo "${ECHO_T}$ac_cv_type_uintptr_t" >&6
 if test $ac_cv_type_uintptr_t = yes; then
 
-cat >>confdefs.h <<\_ACEOF
+cat >>confdefs.h <<_ACEOF
 #define HAVE_UINTPTR_T 1
 _ACEOF
+
 
 fi
 
@@ -4796,10 +4788,7 @@ _ACEOF
 fi
 done
 
-if test -z "$have_snprintf"; then
-	SNPRINTF_C="snprintf.c"
-fi
-if test -z "$have_vsnprintf"; then
+if test -z "$have_snprintf" -o -z "$have_vsnprintf"; then
 	SNPRINTF_C="snprintf.c"
 fi
 
@@ -6361,7 +6350,12 @@ fi;
 # Check whether --enable-small-net or --disable-small-net was given.
 if test "${enable_small_net+set}" = set; then
   enableval="$enable_small_net"
-  small-net=yes; IRC_CFLAGS="$IRC_CFLAGS -DSMALL_NET=1"
+
+	small_net="yes"
+	IRC_CFLAGS="$IRC_CFLAGS -DSMALL_NET"
+
+else
+  small_net="no"
 fi;
 
 # Check whether --enable-efnet or --disable-efnet was given.
@@ -9022,7 +9016,7 @@ echo
 
 echo "Installing into: $prefix"
 
-echo -n "Ziplinks? ................ "
+echo -n "Ziplinks ................ "
 
 if test "$zlib" != no; then
 	echo yes
@@ -9030,7 +9024,7 @@ else
 	echo no
 fi
 
-echo -n "OpenSSL? ................. "
+echo -n "OpenSSL ................. "
 
 if test "X${cf_openssl_ciphers}" != "X"; then
 	echo "yes - ${cf_openssl_ciphers}"
@@ -9038,7 +9032,7 @@ else
 	echo no
 fi
 
-echo -n "Modules? ................. "
+echo -n "Modules ................. "
 
 if test "$ac_cv_shared_modules" = yes; then
 	echo shared
@@ -9046,10 +9040,10 @@ else
 	echo static
 fi
 
-echo  "IPv6 support? ............ $have_v6"
-echo  "Net I/O implementation? .. $SELECT_TYPE"
+echo  "IPv6 support ............ $have_v6"
+echo  "Net I/O implementation .. $SELECT_TYPE"
 
-echo -n "EFnet server? ............ "
+echo -n "EFnet server ............ "
 
 if test "$efnet" = "yes"; then
 	echo "yes (use example.efnet.conf)"
@@ -9057,15 +9051,10 @@ else
 	echo "no (use example.conf)"
 fi
 
-echo -n "Small network? ........... "
-
-if test "$small-net" = yes; then
-	echo yes
-else
-	echo no
-fi
+echo "Small network ........... $small_net"
 
 echo
-
-echo "$as_me:$LINENO: result: Server is configured with NICKLEN=$ac_cv_nicklen TOPICLEN=$ac_cv_topiclen MAX_CLIENTS=$ac_cv_maxclients" >&5
-echo "${ECHO_T}Server is configured with NICKLEN=$ac_cv_nicklen TOPICLEN=$ac_cv_topiclen MAX_CLIENTS=$ac_cv_maxclients" >&6
+echo "Configured limits:"
+echo "NICKLEN ................. $ac_cv_nicklen"
+echo "TOPICLEN ................ $ac_cv_topiclen"
+echo "MAXCLIENTS .............. $ac_cv_maxclients"
