This patch does a number of rather major things, mostly related to Cygwin porting:
configure.ac:
        o Fix a little typo. doesnt -> doesn't
        o Enable CYGWIN handling for uname -s check, preliminary.
        Shared modules will be DISABLED when building on Cygwin. Some
        other hacks are included to get it to nearly build. A lot of the
        additional work that had to be done was because of stu's IPv6
        changes, support of which is not complete in Cygwin yet and
        requires a multitude of unofficial patches to even nearly compile.
        o Also link against Cygwin libraries for Cygwin.
(touches: configure, setup.h.in)

adns/internal.h: Winsock2 headers typedef byte, so make sure we don't do
it again if we're using those headers.

include/stdinc.h: Include some Cygwin headers and not others if we're
using Cygwin.

src/irc_get{name,addr}info.c: Condense the large include list with
#include "stdinc.h".

include/irc_getnameinfo.h, src/irc_getnameinfo.c: Move all of those
#undefs and #defines to where they belong: the header file.

src/s_conf.c, include/s_conf.h: SOCKET_ERROR stomps on Windows's RPC
namespace (or vice versa) which is included for us to build with Winsock2.
Sadly, they're not the same values, so we should change the name, to
IRCD_SOCKET_ERROR (debatable.)

tools/rsa_respond/Makefile: Add *.exe to the clean list.

tools/rsa_respond/respond.c: #include <string.h> to silence $CC about
implicit declaration of strlen and memcpy.

README.FIRST: Cygwin has been broken for a while.

install-sh: patched install-sh to fix licensing issues as discussed
within Debian

Approved by:	stu

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2264,6 +2264,15 @@ echo "${ECHO_T}HP-UX found - Assuming HPUX C compiler cc" >&6
 	OSF*)
 		OSF=yes
 		;;
+	CYGWIN*)
+		CYGWIN=yes
+
+cat >>confdefs.h <<\_ACEOF
+#define CYGWIN 1
+_ACEOF
+
+		LIBS="$LIBS -lws2_32"
+		;;
 esac
 
 echo "$as_me:$LINENO: checking how to generate dependency info" >&5
@@ -6451,11 +6460,18 @@ if test "${enable_shared_modules+set}" = set; then
   ac_cv_shared_modules="no"
 else
 
+
   	if test "$ac_cv_profile" = "no"; then
 		ac_cv_shared_modules="yes"
 	else
-		echo "Shared modules and profiling don't work together."
-		echo "Disabling shared modules."
+		{ echo "$as_me:$LINENO: WARNING: disabling shared modules; cannot coexist with profile builds" >&5
+echo "$as_me: WARNING: disabling shared modules; cannot coexist with profile builds" >&2;}
+		ac_cv_shared_modules="no"
+	fi
+
+	if test "$CYGWIN" = yes; then
+		{ echo "$as_me:$LINENO: WARNING: disabling shared modules; Cygwin is at present unable to build them." >&5
+echo "$as_me: WARNING: disabling shared modules; Cygwin is at present unable to build them." >&2;}
 		ac_cv_shared_modules="no"
 	fi
 
